# Publish GitHub workflow artifacts tutorial example
name: CI

on:
  push:
    branches: 
      - main

jobs:      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: echo ""
  code-quality:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: echo ""
  test:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: echo ""
