# Publish GitHub workflow artifacts tutorial example
name: Staging

on:
  push:
    branches: 
      - main

jobs:      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: echo ""
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: echo ""
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: echo ""
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: echo ""
